export const ALL_GYM_REQUEST = "ALL_GYM_REQUEST";
export const ALL_GYM_SUCCES = "ALL_GYM_SUCCES";
export const ALL_GYM_FAIL = "ALL_GYM_FAIL";

export const SINGLE_GYM_REQUEST = "SINGLE_GYM_REQUEST";
export const SINGLE_GYM_SUCCES = "SINGLE_GYM_SUCCES";
export const SINGLE_GYM_FAIL = "SINGLE_GYM_FAIL";

export const PLAN_REQUEST = "PLAN_REQUEST";
export const PLAN_SUCCES = "PLAN_SUCCES";
export const PLAN_FAIL = "PLAN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
